### PR TITLE
Update from Antlr3.Runtime to Antlr4.Runtime.Standard 4.12.0

### PR DESCRIPTION
**Pull request by markcanary**
- Update Nuget package reference
- Modify NCalc.g from Antlr3 format to Antlr4
- Use Antlr4 program to generate new C# classes from NCalc.g (NCalcBaseListener.cs, NCalcLexer.cs, NCalcListener.cs, NCalcParser.cs)
- Added ErrorListenerLexer and ErrorListenerParser to catch errors using Antlr4 mechanism (Expression.cs, ErrorListeners.cs)
- Removed unneeded files (NCalc.tokens, NCalcLexer.Partial.cs)
- Modified Should_Throw_Exception_On_Lexer_Errors_Issue_6 test to reflect new format of error message in EvaluateException
- All tests are passing

### CODE REVIEW

**Comment by markcanary** [comment]
The Should_Throw_Exception_On_Lexer_Errors_Issue_6 test is failing on the CI build server saying the messages don't match even though they look like they match in the error message. I wonder if the issue is differences in line-feed characters between my system (Windows) and the build server (Linux maybe?) I can try constructing the comparison message in a way that will use the appropriate line ending and see if that helps.

**Comment by markcanary** [comment]
Well, it still doesn't work. I can't see anything different with the expected and actually message returned in the exception. It works just fine on my computer. I have no idea what the problem is.

**Comment by yallie** [comment]
Hello Mark,

thanks a lot for your PR, great job!

For some reason, Github asks for confirmation every time before running the workflow.
I've sent you an invitation to join ncalc organization, hope it'll bypass the confirmation.

Regarding the unit test, you're probably right about the newlines in the error message.
Could you try replacing "\r" and "\n" with empty strings before comparing error messages?
Or just replace the whole `Assert.AreEqual` line with something like 

```csharp
Assert.IsTrue(result2.Message.StartsWith("String '' was not recognized as a valid DateTime."));
```

**Comment by markcanary** [comment]
I go it to pass using your suggestion of 
```
Assert.IsTrue(result2.Message.StartsWith("String '' was not recognized as a valid DateTime."));
``` 
Before that I found a couple line-feeds that I missed in the string and changed those, but it still didn't work. But it is good to go now.

**Comment by yallie** [comment]
Awesome! Thank you :)

**Pull request merged**
